version: "3"

services:

  database:
    container_name: mssql
    build: .
    ports:
      - "1433:1433"
    environment:
      - SA_PASSWORD=Alaska2017
      - ACCEPT_EULA=Y
    volumes:
      - ./mssql:/var/opt/mssql
